language: r
r: bioc-release

before_install:
  - sudo apt-get update
  - sudo apt-get install r-cran-rjags 

# r_build_args: --no-build-vignettesÂ --no-manual --no-resave-data
r_check_args: --no-build-vignettes # --no-manual

#script:
#- travis_wait R CMD build .
#- R CMD check --no-build-vignettes *tar.gz
